### ISSUE TITLE
Step's Title with URL isn't parsed correctly.

### ISSUE THREAD

**Issue by ko4evnik** [allure-framework/allure-core#378]
Title of step is:
"Создание нового пользователя (email: test5416e21badd98@test.com пароль: 864997)"

In XML:

```
 <step start="1.41078312299E+12" stop="1.41078312328E+12" status="passed">
          <name>
                Создание нового пользователя (email: test5416e21badd98@test.com пароль: 864997)
          </name>
 </step>
```

In <uid>-testcase.json:

```
"steps" : [ {
    "name" : "Создание нового пользователя (email: test5416e21badd98@test.com пароль: 864997)",
    "title" : "Com пароль: 864997)"
```

Name is correct, but Title is not. 

```
In report:
[18:14:56.580] Com пароль: 864997)
```

**Comment by eduard-sukharev** [comment]
Guys, can we look at this one more time?
I might be totally wrong, but as stated here allure-framework/allure-php-adapter-api#32 it's not PHP- or Python-specific.
To demonstrate that, have a look at [this synthetic report](https://gist.github.com/eduard-sukharev/7bf92ec7a07bc301ccd541f8392b2d1a):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<alr:test-suite xmlns:alr="urn:model.allure.qatools.yandex.ru" start="1480684292464" stop="1480684651460" version="1.4.0">
  <name>TestSuite-2016-12-02_101132</name>
  <test-cases>
    <test-case start="1480684340540" stop="1480684352813" status="passed">
      <name>dotSomethingInTestSteps</name>
      <title>Test case to demonstrate the problem of dot-something names of test steps rendered incorrectly</title>
      <steps>
        <step start="1480684340546" stop="1480684344682" status="passed">
          <name>Step with title and something.com at the end</name>
          <title>Step with title and something.com at the end</title>
        </step>
        <step start="1480684344683" stop="1480684345390" status="passed">
          <name>Step without title and something.com at the end</name>
        </step>
        <step start="1480684345390" stop="1480684346297" status="passed">
          <name>Step with title and something.com at the end of name only</name>
          <title>Step with title and something with url-like at the end of name only</title>
        </step>
        <step start="1480684346298" stop="1480684346622" status="passed">
          <name>Just a regular step</name>
          <title>Just a regular step</title>
        </step>
      </steps>
    </test-case>
  </test-cases>
</alr:test-suite>
```

The report was edited manually to contain only representable information.
According to [Allure Report XML schema](https://github.com/allure-framework/allure-core/blob/master/allure-model/src/main/resources/allure.xsd#L62) the **title** tag may not present in the step, which implies that **name** tag should be enough.

The result in HTML report looks like this:
![image](https://cloud.githubusercontent.com/assets/3235378/20960541/5f80f6be-bc7a-11e6-8fbf-3b4c32dae088.png)

And this is due to the fact that actually a file in **allure-report/data/**2bcbb778409d2c6e**-testcase.json** contains following information:

```json
{
    "name" : "Step without title and something.com at the end",
    "title" : "Com at the end",
    "time" : {
      "start" : 1480684344683,
      "stop" : 1480684345390,
      "duration" : 707
    },
    "summary" : {
      "attachments" : 0,
      "steps" : 0
    },
    "status" : "PASSED",
    "attachments" : [ ],
    "steps" : [ ]
}
```

All this only means that the problem is somewhere inside Allure Report generation tool, Allure CLI tool, which takes valid XML and chokes on some valid test step names and produces invalid report data representation.
