### ISSUE TITLE
Think more about names and titles in model

### ISSUE THREAD

**Issue by baev** [allure-framework/allure-core#408]
Seems like we should remove name from suites, cases and steps. For now we use name to generate default title, it should match the following regex: `(\w+\.)+\w+[.+]` 

This logic raises many issues

**Comment by clicman** [comment]
@baev Why just not cut off extras on face side? and remove title at all from xml? this solution will be strong and independent of another toolas and implementations. All of truncates should be on ui side. And as additional benefit - it is possible show full string in tittle`s toolyip.
Refactoringcan be done in two steps:
1. On ui side (it will fix bugs like #442)
2. Remove title generation in xml.

What do you think?

**Comment by pupssman** [comment]
@clicman sounds good!

**Comment by baev** [comment]
@clicman yep, you are currently described what we going to do.

**Comment by gazal-k** [comment]
Please forgive my noobness. I was going through https://github.com/allure-framework/allure-core/pull/478 and https://github.com/allure-framework/allure-core/pull/479. I see that the fix is on the HTML report generation side of things. If there are special characters like dot '.', shouldn't they be escaped in the XML report?

**Comment by PavelSusloparovNYT** [comment]
Any updates here?

**Comment by baev** [comment]
fixed in Allure 2 (it has no more titles)
