### ISSUE TITLE
Timeline report is not usable for long running test jobs

### ISSUE THREAD

**Issue by buzdin** [allure-framework/allure-core#571]
If your test run is really long and is distributed on multiple machines timeline results look unusable.

![timeline](https://cloud.githubusercontent.com/assets/299834/7536944/9e5d600e-f58c-11e4-89d1-e7182baaba46.png)

Proper timeline library is required. Should support zooming and timeline horizontal scroll.

**Comment by just-boris** [comment]
+1.
But I didn't see suitable library in open-source. Our requirements:
* Show multiple groups (because we show tests across several hosts)
* Show custom decoration of item and tooltip (we need show status color and tooltip with basic info)
* Allow to listen click on events
* Sufficient performance for several hundreds items on chart
Solutions:
http://bl.ocks.org/bunkat/2338034
http://almende.github.io/chap-links-library/js/timeline/examples/example29_stacking_with_grouping.html
http://timeline.knightlab.com/
http://visjs.org/docs/timeline.html
http://www.simile-widgets.org/timeline/

**Comment by buzdin** [comment]
We have had an investigation and came to conclusion that this one is the easiest lib to hack together such report.

https://almende.github.io/chap-links-library/timeline.html

Will return back once we have more results.

**Comment by baev** [comment]
@buzdin any updates here?

**Comment by buzdin** [comment]
Not yet, still in backlog.

**Comment by baev** [comment]
Ok, I got it

**Comment by baev** [comment]
fixed in https://github.com/allurefw/allure-report/pull/11
