### ISSUE TITLE
Customize report

### ISSUE THREAD

**Issue by OLibutzki** [allure-framework/allure-core#619]
Hi,

is there a way to customize the generated report? I would like to adjust the report in order match my company's corporate identity. Generally it might be sufficient to include a custom css file. Is there any way to do this?

I also would like to add another language beside English and Russian.

Kind regrads
Oliver

**Comment by baev** [comment]
Hi!

> I also would like to add another language beside English and Russian.

Pull requests are welcome! Since 1.4.15 we also supporting Portuguese language https://github.com/allure-framework/allure-core/pull/612

> is there a way to customize the generated report? I would like to adjust the report in order match my company's corporate identity. Generally it might be sufficient to include a custom css file. Is there any way to do this?

In general yes, you can. We are working on plugin API, so you can add custom css to the report. But there is no documentation about plugins yet, the API still in beta (it will be presented in 2.0 release). So you can try to use it (I can prepare sample project for you and maybe answer some questions if you need) or you can just wait 2.0 release.

**Comment by OLibutzki** [comment]
When are you going to release 2.0?

**Comment by baev** [comment]
I have no idea) There is a few important issues we are need to solve. See https://github.com/allure-framework/allure-core/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0.0

**Comment by OLibutzki** [comment]
Ok, thanks...it's not that urgent. If you find the time to document the API (what you have to do for 2.0 anyway I guess), i'm interested in trying it.

Off-topic: I really like what you have built with Allure.It was extremly simple to build an adapter for our test framework.

**Comment by baev** [comment]
Done in Allure 2

**Comment by OLibutzki** [comment]
@baev Where do I find Allure 2 at Github?

**Comment by baev** [comment]
allurefw/allure-report

**Comment by sskorol** [comment]
@baev is it ready to play, or not finished yet?

**Comment by baev** [comment]
Not finished yet. You can read the roadmap at wiki (ru)
