### ISSUE TITLE
allure.issues.tracker.pattern not picking up setting in allure.properties file in TestNG/Gradle/Java configuration

### ISSUE THREAD

**Issue by ChristopherGTaylor** [allure-framework/allure-core#633]

**Comment by shimkiv** [comment]
Please describe how exactly you're generating the report (CLI, Gradle task., etc.) ?

**Comment by ChristopherGTaylor** [comment]
A gradle task that is calling the CLI

task generateAllureReport(type: Exec) {
        commandLine 'allure', 'generate', 'build/allure-results', '-v','1.4.15','-o','build/allure-report'
 }


TestsForDebug.finalizedBy(generateAllureReport)


task openAllureReport(type: Exec) {
        commandLine 'allure', 'report', 'open','-o','build/allure-report'
}


my allure properties file is in the resource folder as instructed on the Wiki
allure.issues.tracker.pattern = https://lifeway.atlassian.net/secure/RapidBoard.jspa?rapidView=90&selectedIssue=%s

**Comment by shimkiv** [comment]
Well, in your case of CLI invocation, you have to be sure that "allure.issues.tracker.pattern" env. var. is available for the "allure-cli". 
Because AFAIK "allure.properties" file can be used only in conjunction with build tool/CI context (allure-maven-plugin for example) to be able to read different properties of your project.
When you invoke "allure" CLI command it knows nothing about your "allure.properties" file.
Look at the "/usr/share/allure/allure-cli/bin/allure" (Debian-based OS, installation from the official repo.) shell script and you will find that "allure" command invokes JAR file.
So you simply can put Java env. var. to that JAR call (java -Dallure.issues.tracker.pattern=https://lifeway.atlassian.net/secure/RapidBoard.jspa?rapidView=90&selectedIssue=%s -jar ${ALLURE_CLI_JAR} $@) or make sure that "allure.issues.tracker.pattern" env. var. is visible for the "allure-cli".

**Comment by shimkiv** [comment]
And don't hesitate to use search next time:
https://github.com/allure-framework/allure-cli/issues?utf8=%E2%9C%93&q=pattern

**Comment by ChristopherGTaylor** [comment]
Sorry. I still can't find anything using search that dealt with my issue. I scoured the documentation and stack overflow as well. 

Thanks for your help thou! I will try to implement your suggestion.
