### ISSUE TITLE
Robot Framework support?

### ISSUE THREAD

**Issue by Tset-Noitamotua** [allure-framework/allure-core#712]
I am wondering why there is no [Robo Framework](http://robotframework.org/) adapter?
Is it because RobotFramework already comes with nice reports and logs out of the box? ;-)

**Comment by baev** [comment]
@Tset-Noitamotua it is because we are don't use Robot Framework at all. So it would be nice if someone implement an adaptor for it.

**Comment by Tset-Noitamotua** [comment]
@baev : Why don´t you use Robot Framework? Have you tried it? It´s the best of all test frameworks! :D 

Is there a documentation about how to implement an adaptor? How much effort does it take?

**Comment by baev** [comment]
> Why don´t you use Robot Framework? Have you tried it? It´s the best of all test frameworks! :D

;-)

> s there a documentation about how to implement an adaptor? How much effort does it take?

In few words: https://github.com/allure-framework/allure-core/wiki/Creating-Allure-Adapter

**Comment by dnekhayev** [comment]
> Is there a documentation about how to implement an adaptor? How much effort does it take?

You should use RF Listener API in order to attach Allure reports to the Robot Framework.
It isn't too hard task (for 1 evening I think ;) )
But also you may need to solve several additional problems, for example:
1. Exception's stack trace suppressing (its useless in java)
2. Storing Allure's metadata information in RF test suites.
3. Storing custom data as an attachments to Allure's steps.
