### ISSUE TITLE
is it possible to update fail status to pass after manual test

### ISSUE THREAD

**Issue by thasherwin** [allure-framework/allure-core#774]
Is it possible to update the report status to pass after manual test? Sometimes a test fails because an environment was not available. So sometimes I test manually a functionality and I would like to update the status to pass. Would be nice if this is possible.

**Comment by just-boris** [comment]
I guess you are looking for a way to resolve test case from a browser.
It is not technically possible. Allure is the only bunch of static files, and there is no way to update them from the browser.

This also tightly coupled with your CI-server that you use, because it stores your tests results, maybe it has a way to update it, but not from Allure.

**Comment by thasherwin** [comment]
That's fast. yes, that's what I am looking for. Thank you for the quick reply. I do hope that there is someone who has done this before.

**Comment by baev** [comment]
@thasherwin I guess this should be done via some sort of TMS
