### ISSUE TITLE
Mark test steps as failed or broken

### ISSUE THREAD

**Issue by golauty** [allure-framework/allure-core#879]
Hi,
i am using protractor / jasmine for my test suites and i want to mark a failing allure test step as "broken" or "failed". 

Usually i use something like
``
allure.createStep('Test step', function() =
 {
expect(test).toEqual("test")
}
``
When expect fails i get an error for the whole testcase but not for the test step.

If i throw an error inside createStep function, the test step will be marked as "broken".

Can i somehow set this test step status ?

**Comment by just-boris** [comment]
Hello!

This is a technical problem with Jasmine at all. It swallows the exception, so Allure doesn't see it until the test will end.

To work this around, I'd recommend you to use another assertion library, rather than Jasmine's standard. For, example, you can take built-in node.js lib from `assert` module.

```js
const assert = require('assert');

const myStep = allure.createStep('step name', () => assert.equals(test, 'a val'));
```

Then the error will be thrown appropriately, and Allure will see it.

:warning: This is not recommended way, there may be some other incompatibilities, because Jasmine is not designed to work with external assertion libs, but if you want better reporting in Allure, you have to go that way.
